import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Hillary Santos | Portfólio",
  description: "Generated by Hillary Santos",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" type="image" href="img/meuAvatar.png" />
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
